# Generated by Django 3.1.2 on 2020-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('courseNumber', models.IntegerField(unique=True)),
                ('instructorName', models.CharField(blank=True, max_length=60)),
                ('duration', models.FloatField(blank=True)),
            ],
        ),
    ]
